config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get "welcome/index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"

  get "main/index"
  get "profile", to: "main#profile"
  get "games", to: "main#games"
  get "details", to: "main#details"
  get "streams", to: "main#streams"

  resources :browse, only: [:index] do
    get :search, on: :collection
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :developers
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :publishers

  has_one_attached :picture
  has_one_attached :background_image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  before_action :load_resources, only: [:index, :search]

  def index
    @pagy, @games = pagy(Game.all)
  end

  def search
    @pagy, @games = pagy(filter_games)
    render :index
  end

  private

  def search_params
    params.require(:filter).permit(:title, :platform_id, :genre_id)
  end

  def filter_games
    games = Game.includes(:genres, :platforms)
    games = games.where('games.title ilike ?', "%#{search_params[:title]}%") if search_params[:title].present?
    games = games.where(genres: { id: search_params[:genre_id] }) if search_params[:genre_id].present?
    games = games.where(platforms: { id: search_params[:platform_id] }) if search_params[:platform_id].present?
    games
  end

  def load_resources
    @platforms = Platform.all.order(:name)
    @genres = Genre.all.order(:title)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def profile
  end

  def details
  end

  def streams
  end

  def games
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/shared/_images.html.erb
<div> <%= image_tag main_app.url_for(instance.picture) if instance.picture.attached? %> </div>
<hr>
<div> <%= image_tag main_app.url_for(instance.background_image) if instance.background_image.attached? %> </div>

app/views/browse/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">
        <!-- ***** Most Popular Start ***** -->
        <div class="most-popular">
          <div class="row">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4>Lista de jogos</h4>
              </div>

              <%= form_with(scope: :filter, url: search_browse_index_path, method: :get, class: 'd-flex') do |f| %>
                <div class="field w-100">
                  <%= f.text_field :title, placeholder: 'Digite o nome do jogo', class: 'form-control me-2', value: params.dig(:filter, :title) %>
                </div>

                <div class="field w-100 px-3">
                  <%= f.collection_select :platform_id, @platforms, :id, :name, 
                    { include_blank: "Todos", prompt: "Selecione a plataforma", selected: params.dig(:filter, :platform_id)}, 
                    { class: "form-control", onchange: "this.form.submit()" } 
                  %>
                </div>

                <div class="field w-100">
                  <%= f.collection_select :genre_id, @genres, :id, :title, 
                    { include_blank: "Todos", prompt: "Selecione o gênero", selected: params.dig(:filter, :genre_id) }, 
                    { class: "form-control", onchange: "this.form.submit()" } 
                  %>
                </div>
              <% end %>

              <div class="row">
                <% @games.each do |game| %>
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <%= 
                        image_tag main_app.url_for(game.picture), 
                        width: 230, 
                        height: 168, 
                        class: 'image-fit' if game.picture.attached? 
                      %>
                      <h4 class='mb-2'>
                        <%= game.title %>
                      </h4>

                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Adicionar
                        </button>
                        <ul class="dropdown-menu w-100">
                          <li><a class="dropdown-item text-center" href="#">Finalizei</a></li>
                          <li><a class="dropdown-item text-center" href="#">Tenho</a></li>
                          <li><a class="dropdown-item text-center" href="#">Quero</a></li>
                          <li><a class="dropdown-item text-center" href="#">Sei la</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>

              <!-- Pagination controls -->
              <div class="row">
                <div class="d-flex justify-content-center mt-4">
                  <%== pagy_bootstrap_nav(@pagy) %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Most Popular End ***** -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameoteca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/main/browse.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">
        <!-- ***** Most Popular Start ***** -->
        <div class="most-popular">
          <div class="row">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4>Lista de jogos</h4>
              </div>

              <div class='row mb-4'>
                <div class='col'>
                  <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Digite o nome do jogo" aria-label="Search">
                  </form>
                </div>
                
                <div class='col'>
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Plataformas
                    </button>
                    <ul class="dropdown-menu w-100">
                      <li><a class="dropdown-item text-center" href="#">Finalizei</a></li>
                      <li><a class="dropdown-item text-center" href="#">Tenho</a></li>
                      <li><a class="dropdown-item text-center" href="#">Quero</a></li>
                      <li><a class="dropdown-item text-center" href="#">Sei la</a></li>
                    </ul>
                  </div>
                </div>

                <div class='col'>
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Gêneros
                    </button>
                    <ul class="dropdown-menu w-100">
                      <li><a class="dropdown-item text-center" href="#">Finalizei</a></li>
                      <li><a class="dropdown-item text-center" href="#">Tenho</a></li>
                      <li><a class="dropdown-item text-center" href="#">Quero</a></li>
                      <li><a class="dropdown-item text-center" href="#">Sei la</a></li>
                    </ul>
                  </div>
                </div>
                
              </div>


              <div class="row">
                <% @games.each do |game| %>
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <%= 
                        image_tag main_app.url_for(game.picture), 
                        width: 230, 
                        height: 168, 
                        class: 'image-fit' if game.picture.attached? 
                      %>
                      <h4 class='mb-2'>
                        <%= game.title %>
                      </h4>

                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Adicionar
                        </button>
                        <ul class="dropdown-menu w-100">
                          <li><a class="dropdown-item text-center" href="#">Finalizei</a></li>
                          <li><a class="dropdown-item text-center" href="#">Tenho</a></li>
                          <li><a class="dropdown-item text-center" href="#">Quero</a></li>
                          <li><a class="dropdown-item text-center" href="#">Sei la</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Most Popular End ***** -->
      </div>
    </div>
  </div>
</div>

app/views/main/details.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">

        <!-- ***** Featured Start ***** -->
        <div class="row">
          <div class="col-lg-12">
            <div class="feature-banner header-text">
              <div class="row">
                <div class="col-lg-4">
                  <%= image_tag "feature-left", style:"border-radius: 23px;" %>
                </div>
                <div class="col-lg-8">
                  <div class="thumb">
                    <%= image_tag "feature-right.jpg", style:"border-radius: 23px;"%>
                    <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Featured End ***** -->

        <!-- ***** Details Start ***** -->
        <div class="game-details">
          <div class="row">
            <div class="col-lg-12">
              <h2>Fortnite Details</h2>
            </div>
            <div class="col-lg-12">
              <div class="content">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="left-info">
                      <div class="left">
                        <h4>Fortnite</h4>
                        <span>Sandbox</span>
                      </div>
                      <ul>
                        <li><i class="fa fa-star"></i> 4.8</li>
                        <li><i class="fa fa-download"></i> 2.3M</li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="right-info">
                      <ul>
                        <li><i class="fa fa-star"></i> 4.8</li>
                        <li><i class="fa fa-download"></i> 2.3M</li>
                        <li><i class="fa fa-server"></i> 36GB</li>
                        <li><i class="fa fa-gamepad"></i> Action</li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <%= image_tag "details-01", style: "border-radius: 23px; margin-bottom: 30px;"%>
                  </div>
                  <div class="col-lg-4">
                    <%= image_tag "details-02", style: "border-radius: 23px; margin-bottom: 30px;"%>
                  </div>
                  <div class="col-lg-4">
                    <%= image_tag "details-03", style: "border-radius: 23px; margin-bottom: 30px;"%>
                  </div>
                  <div class="col-lg-12">
                    <p>Cyborg Gaming is free HTML CSS website template provided by TemplateMo. This is Bootstrap v5.2.0 layout. You can make a <a href="https://paypal.me/templatemo" target="_blank">small contribution via PayPal</a> to info [at] templatemo.com and thank you for supporting. If you want to get the PSD source files, please contact us. Lorem ipsum dolor sit consectetur es dispic dipiscingei elit, sed doers eiusmod lisum hored tempor.</p>
                  </div>
                  <div class="col-lg-12">
                    <div class="main-border-button">
                      <a href="#">Download Fortnite Now!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Details End ***** -->

        <!-- ***** Other Start ***** -->
        <div class="other-games">
          <div class="row">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4><em>Other Related</em> Games</h4>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-01", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-02", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-03", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-02", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-03", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="item">
                <%= image_tag "game-01", class:"templatemo-item" %>
                <h4>Dota 2</h4><span>Sandbox</span>
                <ul>
                  <li><i class="fa fa-star"></i> 4.8</li>
                  <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Other End ***** -->

      </div>
    </div>
  </div>
</div>

app/views/main/games.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">

      </div>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">

        <!-- ***** Banner Start ***** -->
        <div class="main-banner">
          <div class="row">
            <div class="col-lg-7">
              <div class="header-text">
                <h6>Welcome To Cyborg</h6>
                <h4><em>Browse</em> Our Popular Games Here</h4>
                <div class="main-button">
                  <a href="browse.html">Browse Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Banner End ***** -->

        <!-- ***** Most Popular Start ***** -->
        <div class="most-popular">
          <div class="row">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4><em>Most Popular</em> Right Now</h4>
              </div>
              <div class="row">
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-01"%>
                    <h4>Fortnite<br><span>Sandbox</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-02"%>
                    <h4>PubG<br><span>Battle S</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-03"%>
                    <h4>Dota2<br><span>Steam-X</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-04"%>
                    <h4>CS-GO<br><span>Legendary</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="item">
                    <div class="row">
                      <div class="col-lg-6 col-sm-6">
                        <div class="item inner-item">
                          <%= image_tag "popular-05"%>
                          <h4>Mini Craft<br><span>Legendary</span></h4>
                          <ul>
                            <li><i class="fa fa-star"></i> 4.8</li>
                            <li><i class="fa fa-download"></i> 2.3M</li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-lg-6 col-sm-6">
                        <div class="item">
                          <%= image_tag "popular-06"%>
                          <h4>Eagles Fly<br><span>Matrix Games</span></h4>
                          <ul>
                            <li><i class="fa fa-star"></i> 4.8</li>
                            <li><i class="fa fa-download"></i> 2.3M</li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-07"%>
                    <h4>Warface<br><span>Max 3D</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <%= image_tag "popular-08"%>
                    <h4>Warcraft<br><span>Legend</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> 4.8</li>
                      <li><i class="fa fa-download"></i> 2.3M</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="main-button">
                    <a href="browse.html">Discover Popular</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Most Popular End ***** -->

        <!-- ***** Gaming Library Start ***** -->
        <div class="gaming-library">
          <div class="col-lg-12">
            <div class="heading-section">
              <h4><em>Your Gaming</em> Library</h4>
            </div>
            <div class="item">
              <ul>
                <li><%= image_tag "game-01.jpg", class:"templatemo-item"%></li>
                <li><h4>Dota 2</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>24/08/2036</span></li>
                <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
              </ul>
            </div>
            <div class="item">
              <ul>
                <li><%= image_tag "game-02.jpg", class:"templatemo-item"%></li>
                <li><h4>Fortnite</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>22/06/2036</span></li>
                <li><h4>Hours Played</h4><span>740 H 52 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button"><a href="#">Donwload</a></div></li>
              </ul>
            </div>
            <div class="item last-item">
              <ul>
                <li><%= image_tag "game-03.jpg", class:"templatemo-item"%></li>
                <li><h4>CS-GO</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>21/04/2036</span></li>
                <li><h4>Hours Played</h4><span>892 H 14 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-12">
            <div class="main-button">
              <a href="profile.html">View Your Library</a>
            </div>
          </div>
        </div>
        <!-- ***** Gaming Library End ***** -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p>© 2025 <a href="#">Gameoteca</a>. Todos os direitos reservados. 
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <nav class="main-nav">
                  <!-- ***** Logo Start ***** -->
                  <div class="heading-section">
                    <h4>Gameoteca</h4>
                  </div>

                  <%= link_to root_path, class: 'logo' do %>
                      <%= image_tag('gameoteca_logo_red_no_bg', style: "width: 120px;top: -35px;position: relative;") %>
                  <% end %>
                  
                  <!-- ***** Logo End ***** -->
                  <!-- ***** Search End ***** -->
                  <div class="search-input">
                    <form id="search" action="#">
                      <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                      <i class="fa fa-search"></i>
                    </form>
                  </div>
                  <!-- ***** Search End ***** -->
                  <!-- ***** Menu Start ***** -->
                  <ul class="nav">
                      <li>
                        <%= link_to 'Home', root_path %>
                      </li>
                      <li>
                        <%= link_to 'Jogos', browse_index_path %>
                      </li>
                      <li>
                        <%= link_to 'Details', details_path %>
                      </li>
                      <li>
                        <%= link_to 'Streams', streams_path %>
                      </li>
                      <li>
                        <%= link_to profile_path do %>
                          Profile
                          <%= image_tag "profile-header" %>
                        <% end %>
                      </li>
                  </ul>   
                  <a class='menu-trigger'>
                      <span>Menu</span>
                  </a>
                  <!-- ***** Menu End ***** -->
              </nav>
          </div>
      </div>
  </div>
</header>
<!-- ***** Header Area End ***** -->

app/views/welcome/index.html.erb
<h1>Welcome</h1>


<h2>Stimulus Check</h2>

<div data-controller="hello">
  <input data-hello-target="name" type="text">

  <button data-action="click->hello#greet">
    Greet
  </button>

  <span data-hello-target="output">
  </span>
</div>